/**
 * SR-2026-052 item 2.2 (SEC-AI-002): wherever a student meets the persona or
 * its feedback, the page says plainly that both are AI-generated and play no
 * part in grading. Nothing in this application writes to a gradebook.
 */
export const AI_NOTICE_TEXT =
  'The stakeholder and your feedback are generated by AI. They are for practice only and do not affect your grade.'

export function AiNotice({ className = '' }: { className?: string }) {
  return (
    <p
      role="note"
      data-testid="ai-notice"
      className={`border-l-[3px] border-brand-rose bg-page px-3.5 py-2.5 text-[13px] leading-[1.55] text-muted ${className}`}
    >
      <span className="font-semibold text-ink">AI-generated · not graded.</span> {AI_NOTICE_TEXT}
    </p>
  )
}
