"""The pre-session notice a student acknowledges before every interview.

SR-2026-052 item 1.2 / Solution Architecture §4.1: the student is told the
session is recorded and processed by AI, and not to share real personal,
family or health information. The server holds the canonical text and its
version; starting an interview requires acknowledging *this* version, and the
version is stored on the session. Change the wording → bump the version, so a
stored acknowledgement always names the text that was actually shown.
"""

from __future__ import annotations

from fastapi import APIRouter
from pydantic import BaseModel

NOTICE_VERSION = "2026-10-01"

router = APIRouter()


class Notice(BaseModel):
    version: str
    title: str
    points: list[str]
    acknowledgement: str


NOTICE = Notice(
    version=NOTICE_VERSION,
    title="Before you start",
    points=[
        "This interview is recorded as a written transcript. Your voice is sent to "
        "an AI service to produce the transcript and the stakeholder's replies.",
        "Audio is not saved. Only the written transcript is kept, and only for "
        "the period set by the course's retention schedule.",
        "The stakeholder is a fictional AI character. Do not share real personal, "
        "family, health or financial information about yourself or anyone else.",
        "Your work is stored under a pseudonymous ID, not your name.",
        "Your feedback is generated by AI. It is formative only and does not "
        "affect your grade.",
    ],
    acknowledgement="I understand. Start the interview.",
)


@router.get("/realtime/notice", response_model=Notice)
async def get_notice() -> Notice:
    return NOTICE
