"""Student self-export (SR-2026-052 item 1.9, SEC-DATA-001).

SES holds no graded work: students download their OWN materials and submit
them to their instructor outside the system. Everything here is scoped to the
caller's participant_id; someone else's session answers 404, exactly like
every other ownership check. Read-only — nothing is graded or written back.

The download is a zip with, per interview: the transcript (readable text and
JSON) and the feedback report (readable Markdown and JSON). SES stores no
interview guides or reflections; the README says so, so a student is never
left wondering whether something is missing.
"""

from __future__ import annotations

import io
import json
import zipfile
from datetime import datetime, timezone
from typing import Annotated, Any, Optional
from uuid import UUID

from fastapi import APIRouter, Depends, Request, Response

from app.api.eval import _item_display_state
from app.auth.dependencies import CurrentUser, deny_session_access, rate_limited, require_user
from app.db import get_pool
from app.observability.audit import audit
from app.personas.prompt_assembly import get_available_personas

router = APIRouter()

_EXPORT_LIMIT = ("self-export", 30, 3600)

# Mirrors frontend/src/score/copy.ts so the download reads like the report.
_DIMENSION_LABELS = {
    "framing_and_stakeholder_fit": "Framing & Fit",
    "question_quality_and_precision": "Question Quality",
    "probing_and_follow_up_depth": "Follow-Up Depth",
    "listening_interpretation_and_stewardship": "Listening & Interpretation",
}
_STATE_LABELS = {"earned": "Earned", "opened": "Opened", "not_opened": "Not opened"}

README = """Stakeholder Engagement Simulator — your interview materials
==========================================================

This download contains your OWN interviews, as stored by SES:

  transcript.txt / transcript.json   what you and the stakeholder said
  feedback.md / feedback.json        your feedback report, if the interview was scored

The feedback is generated by AI. It is formative only and is not a grade.
SES does no grading; submit these files to your instructor yourself if your
course asks you to.

Not included, because SES does not store them: interview guides and written
reflections. Add your own if your instructor asks for them.

Files are labelled with your pseudonymous ID, not your name.
"""


def _persona_names() -> dict[str, str]:
    return {p["key"]: p["display_name"] for p in get_available_personas()}


def _parse(raw: Any) -> Any:
    return json.loads(raw) if isinstance(raw, str) else raw


def _transcript_text(turns: list[dict], persona_name: str, purged: bool) -> str:
    if purged:
        return "This interview's content was removed after review.\n"
    if not turns:
        return "(No conversation was recorded for this interview.)\n"
    lines = []
    for t in turns:
        speaker = "You" if t.get("role") == "user" else persona_name
        text = (t.get("text") or "").strip()
        if text:
            lines.append(f"{speaker}: {text}\n")
    return "\n".join(lines)


def _feedback_markdown(evaluation: dict, persona_name: str) -> str:
    out = [
        f"# Feedback report — interview with {persona_name}",
        "",
        "_Generated by AI. Formative only — this is not a grade._",
        "",
        f"**Overall:** {evaluation.get('overall_score', '—')} / 10"
        f" · {evaluation.get('skill_label', '')}".rstrip(" ·"),
        "",
        "## How you interviewed",
    ]
    for d in evaluation.get("dimensions") or []:
        label = _DIMENSION_LABELS.get(d.get("dimension"), d.get("dimension", ""))
        out += ["", f"### {label} — {d.get('score', '—')} / 10", "", d.get("assessment", "")]

    moments = evaluation.get("moments") or []
    if moments:
        out += ["", "## Key moments"]
        for m in moments:
            out += ["", f"### {m.get('headline', '')}", ""]
            if m.get("persona_offered"):
                out.append(f"- **{persona_name} offered:** {m['persona_offered']}")
            out.append(f"- **You said:** “{m.get('student_quote', '')}”")
            out.append(f"- **What it produced:** {m.get('what_it_produced', '')}")
            out.append(f"- **Outcome:** {m.get('outcome', '')}")
            if m.get("technique_name"):
                out.append(f"- **Try:** {m['technique_name']} — {m.get('technique_stem', '')}")

    coverage = evaluation.get("insight_coverage") or []
    if coverage:
        out += ["", "## What you learned"]
        for tier in coverage:
            out += ["", f"### {tier.get('title') or 'Tier ' + str(tier.get('tier', ''))}"]
            if tier.get("description"):
                out += ["", tier["description"]]
            items = tier.get("items") or []
            if items:
                out.append("")
                for item in items:
                    state = _STATE_LABELS[_item_display_state(item)]
                    out.append(f"- {item.get('display_label') or item.get('fact_summary', '')} — {state}")
    return "\n".join(out).rstrip() + "\n"


async def _own_sessions(conn, participant_id: UUID, session_id: Optional[UUID] = None):
    return await conn.fetch(
        """
        SELECT s.id, s.persona_id, s.started_at, s.transcript, s.purged_at,
               (SELECT e.evaluation FROM session_evaluations e
                 WHERE e.session_id = s.id ORDER BY e.created_at DESC LIMIT 1) AS evaluation
        FROM interview_sessions s
        WHERE s.participant_id = $1 AND ($2::uuid IS NULL OR s.id = $2)
        ORDER BY s.started_at
        """,
        participant_id, session_id,
    )


def _build_zip(rows, code: str) -> bytes:
    names = _persona_names()
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.txt", README)
        for row in rows:
            persona_name = names.get(row["persona_id"], row["persona_id"] or "Stakeholder")
            started = row["started_at"] or datetime.now(timezone.utc)
            folder = f"{started:%Y-%m-%d_%H%M}_{row['persona_id']}_{str(row['id'])[:8]}"
            purged = row["purged_at"] is not None
            turns = [] if purged else (_parse(row["transcript"]) or [])
            zf.writestr(f"{folder}/transcript.txt", _transcript_text(turns, persona_name, purged))
            zf.writestr(
                f"{folder}/transcript.json",
                json.dumps(
                    {"session_id": str(row["id"]), "pseudonymous_id": code,
                     "persona": persona_name, "started_at": started.isoformat(), "turns": turns},
                    indent=2, ensure_ascii=False,
                ),
            )
            evaluation = _parse(row["evaluation"])
            if evaluation and not purged:
                zf.writestr(f"{folder}/feedback.md", _feedback_markdown(evaluation, persona_name))
                zf.writestr(
                    f"{folder}/feedback.json",
                    json.dumps(evaluation, indent=2, ensure_ascii=False),
                )
    return buf.getvalue()


def _zip_response(content: bytes, filename: str) -> Response:
    return Response(
        content=content,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Cache-Control": "no-store",
        },
    )


async def _code(conn, participant_id: UUID) -> str:
    return await conn.fetchval(
        "SELECT pseudonymous_code FROM participants WHERE participant_id = $1", participant_id
    )


@router.get("/export/sessions/{session_id}", dependencies=[Depends(rate_limited(*_EXPORT_LIMIT))])
async def export_one(
    session_id: UUID, request: Request, user: Annotated[CurrentUser, Depends(require_user)]
) -> Response:
    pool = await get_pool()
    async with pool.acquire() as conn:
        rows = await _own_sessions(conn, user.participant_id, session_id)
        if not rows:
            owner = await conn.fetchval(
                "SELECT participant_id FROM interview_sessions WHERE id = $1", session_id
            )
            deny_session_access(session_id, user, owner)
        code = await _code(conn, user.participant_id)
    audit(
        "export.self", "success", actor_user_id=user.id, participant_id=user.participant_id,
        request=request, session_count=1, session_id=session_id,
    )
    return _zip_response(_build_zip(rows, code), f"ses-{code}-{str(session_id)[:8]}.zip")


@router.get("/export/me", dependencies=[Depends(rate_limited(*_EXPORT_LIMIT))])
async def export_all(
    request: Request, user: Annotated[CurrentUser, Depends(require_user)]
) -> Response:
    pool = await get_pool()
    async with pool.acquire() as conn:
        rows = await _own_sessions(conn, user.participant_id)
        code = await _code(conn, user.participant_id)
    audit(
        "export.self", "success", actor_user_id=user.id, participant_id=user.participant_id,
        request=request, session_count=len(rows),
    )
    return _zip_response(_build_zip(rows, code), f"ses-{code}-all-interviews.zip")
